export default [
  {
    "id": 1,
    "name": "John Doe",
    "picture": "https://randomuser.me/api/portraits/men/1.jpg",
    "email": "john@example.com",
    "days_since_contact": 12,
    "status": "overdue",
    "tags": ["college", "close friend"],
    "bio": "Met in university. Love hiking together.",
    "goal": 14,
    "next_due_date": "2025-07-20"
  },
  {
    "id": 2,
    "name": "Sarah Johnson",
    "picture": "https://randomuser.me/api/portraits/women/2.jpg",
    "email": "sarah@example.com",
    "days_since_contact": 5,
    "status": "on_track",
    "tags": ["work", "mentor"],
    "bio": "Former team lead. Always gives great career advice.",
    "goal": 7,
    "next_due_date": "2025-07-12"
  },
  {
    "id": 3,
    "name": "Michael Brown",
    "picture": "https://randomuser.me/api/portraits/men/3.jpg",
    "email": "michael@example.com",
    "days_since_contact": 20,
    "status": "overdue",
    "tags": ["gym", "friend"],
    "bio": "Workout partner since 2023.",
    "goal": 14,
    "next_due_date": "2025-07-05"
  },
  {
    "id": 4,
    "name": "Emily Davis",
    "picture": "https://randomuser.me/api/portraits/women/4.jpg",
    "email": "emily@example.com",
    "days_since_contact": 2,
    "status": "on_track",
    "tags": ["family", "cousin"],
    "bio": "Lives in another city. We video call often.",
    "goal": 10,
    "next_due_date": "2025-07-18"
  },
  {
    "id": 5,
    "name": "David Wilson",
    "picture": "https://randomuser.me/api/portraits/men/5.jpg",
    "email": "david@example.com",
    "days_since_contact": 9,
    "status": "due_soon",
    "tags": ["college", "roommate"],
    "bio": "Shared an apartment during college.",
    "goal": 10,
    "next_due_date": "2025-07-14"
  },
  {
    "id": 6,
    "name": "Sophia Martinez",
    "picture": "https://randomuser.me/api/portraits/women/6.jpg",
    "email": "sophia@example.com",
    "days_since_contact": 1,
    "status": "on_track",
    "tags": ["book club", "friend"],
    "bio": "Enjoys reading mystery novels.",
    "goal": 7,
    "next_due_date": "2025-07-09"
  },
  {
    "id": 7,
    "name": "James Anderson",
    "picture": "https://randomuser.me/api/portraits/men/7.jpg",
    "email": "james@example.com",
    "days_since_contact": 16,
    "status": "overdue",
    "tags": ["neighbor"],
    "bio": "Friendly neighbor who loves gardening.",
    "goal": 14,
    "next_due_date": "2025-07-08"
  },
  {
    "id": 8,
    "name": "Olivia Taylor",
    "picture": "https://randomuser.me/api/portraits/women/8.jpg",
    "email": "olivia@example.com",
    "days_since_contact": 6,
    "status": "on_track",
    "tags": ["travel", "friend"],
    "bio": "Met while traveling in Japan.",
    "goal": 10,
    "next_due_date": "2025-07-15"
  },
  {
    "id": 9,
    "name": "Daniel Thomas",
    "picture": "https://randomuser.me/api/portraits/men/9.jpg",
    "email": "daniel@example.com",
    "days_since_contact": 13,
    "status": "due_soon",
    "tags": ["startup", "co-founder"],
    "bio": "Worked together on a side project.",
    "goal": 14,
    "next_due_date": "2025-07-16"
  },
  {
    "id": 10,
    "name": "Emma White",
    "picture": "https://randomuser.me/api/portraits/women/10.jpg",
    "email": "emma@example.com",
    "days_since_contact": 3,
    "status": "on_track",
    "tags": ["school", "best friend"],
    "bio": "Known each other since high school.",
    "goal": 7,
    "next_due_date": "2025-07-11"
  }
]